In [19]:
import pandas as pd

In [24]:
price = pd.read_csv('price_demand_data.csv')
price

      REGION    SETTLEMENTDATE  TOTALDEMAND PRICECATEGORY
0       VIC1    1/01/2021 0:30      4179.21           LOW
1       VIC1    1/01/2021 1:00      4047.76           LOW
2       VIC1    1/01/2021 1:30      3934.70           LOW
3       VIC1    1/01/2021 2:00      3766.45           LOW
4       VIC1    1/01/2021 2:30      3590.37           LOW
...      ...               ...          ...           ...
11659   VIC1  31/08/2021 22:00      4861.91        MEDIUM
11660   VIC1  31/08/2021 22:30      4748.74        MEDIUM
11661   VIC1  31/08/2021 23:00      4620.09        MEDIUM
11662   VIC1  31/08/2021 23:30      4834.00        MEDIUM
11663   VIC1    1/09/2021 0:00      4811.27        MEDIUM

[11664 rows x 4 columns]

In [21]:
date = list(price['SETTLEMENTDATE'])

In [23]:
date[0].split()

['1/01/2021', '0:30']

In [5]:
weather = pd.read_csv('weather_data.csv')

In [6]:
display(weather)

,Date,Minimum temperature (°C),Maximum temperature (°C),Rainfall (mm),Evaporation (mm),Sunshine (hours),Direction of maximum wind gust,Speed of maximum wind gust (km/h),Time of maximum wind gust,9am Temperature (°C),...,9am cloud amount (oktas),9am wind direction,9am wind speed (km/h),9am MSL pressure (hPa),3pm Temperature (°C),3pm relative humidity (%),3pm cloud amount (oktas),3pm wind direction,3pm wind speed (km/h),3pm MSL pressure (hPa)
0,1/01/2021,15.6,29.9,0.0,2.8,9.3,NNE,31.0,13:14,19.2,...,6,N,2,1018.8,28.1,43,5.0,E,13,1015.3
1,2/01/2021,18.4,29.0,0.0,9.4,1.3,NNW,30.0,8:22,23.3,...,7,NNW,17,1013.3,28.7,38,7.0,SW,4,1008.5
2,3/01/2021,17.0,26.2,12.6,4.8,7.1,WSW,33.0,17:55,18.3,...,8,WSW,4,1007.7,23.5,59,4.0,SSW,2,1005.2
3,4/01/2021,16.0,18.6,2.6,3.8,0.0,SSE,41.0,16:03,16.2,...,8,SSE,11,1010.0,18.2,82,8.0,SSW,17,1011.0
4,5/01/2021,15.9,19.1,11.2,1.0,0.0,SSE,35.0,11:02,17.2,...,8,SSE,13,1012.5,18.2,82,8.0,SSE,19,1013.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,27/08/2021,4.6,13.6,0.0,1.2,3.8,SSW,15.0,12:18,7.7,...,7,,Calm,1020.0,12.8,65,7.0,SSE,7,1017.4
239,28/08/2021,5.3,17.8,0.0,1.6,9.6,N,39.0,13:14,9.1,...,1,N,7,1018.6,17.4,31,3.0,NNW,24,1013.5
240,29/08/2021,9.1,16.2,0.6,6.4,4.3,NNE,33.0,1:50,10.6,...,7,N,13,1011.4,12.8,84,7.0,S,6,1010.4
241,30/08/2021,6.4,17.6,4.0,1.4,7.4,NNW,50.0,14:04,11.1,...,7,N,15,1016.1,16.8,45,1.0,NNW,28,1013.2
242,31/08/2021,11.0,20.1,0.0,5.8,3.6,N,61.0,16:29,13.5,...,7,N,17,NaN,19.4,43,6.0,N,30,1012.2